---
- name: Запуск скрипта установки RabbitMQ
  ansible.builtin.script:
    cmd: '{{ role_path }}/files/install_rabbitmq.sh'
    creates: /var/lib/rabbitmq/setup_done

- name: Остановка и полная очистка перед созданием кластера
  block:
    - ansible.builtin.systemd:
        name: rabbitmq-server
        state: stopped
 
    - ansible.builtin.file:
        path: /var/lib/rabbitmq/mnesia/
        state: absent

- name: Добавление конфига rabbitmq.conf
  ansible.builtin.blockinfile:
    path: /etc/rabbitmq/rabbitmq.conf
    create: yes
    marker: "# {mark} RABBITMQ CLUSTER NODES #"
    block: |
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
      {% for host in groups['rabbitmq_cluster'] %}
      cluster_formation.classic_config.nodes.{{ loop.index }} = rabbit@{{ hostvars[host]['hostname'] }}
      {% endfor %}
    owner: rabbitmq
    group: rabbitmq
    mode: '0644'
  notify: Restart RabbitMQ

- name: Добавление хостов кластера в /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['hostname'] }}"
    regexp: ".*{{ hostvars[item]['hostname'] }}$"
    state: present
  loop: "{{ groups['rabbitmq_cluster'] }}"

- name: Добавление ключа erlang.cookie
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: '0400'
  notify: Restart RabbitMQ

- name: Включение плагина Management
  ansible.builtin.copy:
    content: "[rabbitmq_management]."
    dest: /etc/rabbitmq/enabled_plugins
    owner: rabbitmq
    group: rabbitmq
    mode: '0644'

- name: start RabbitMQ
  ansible.builtin.systemd:
   name: rabbitmq-server
   state: started

- name: Ожидание готовности RabbitMQ (проверка порта)
  ansible.builtin.wait_for:
    port: 5672
    delay: 2
    timeout: 30

- name: Создание администратора для Web UI (через CLI)
  ansible.builtin.shell: |
    rabbitmqctl add_user admin {{ rmq_pass }} || rabbitmqctl change_password admin {{ rmq_pass }}
    rabbitmqctl set_user_tags admin administrator
    rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
  changed_when: false
